version: "3.8"

services:
  api:
    build: .
    container_name: realworld-api
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/realworld
      SECRET: supersecretkey
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: realworld-mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
